<script lang="ts">
	import type { CoachingResponse } from '$lib/types';
	import { Card } from '$lib/components/ui';

	interface Props {
		coaching: CoachingResponse;
	}

	let { coaching }: Props = $props();
</script>

<Card>
	<div class="mb-6">
		<h2 class="text-lg font-semibold text-slate-900">AI Coaching & Rulebook</h2>
		<p class="mt-1 text-sm text-slate-500">
			Generated by Claude based on your anonymized behavioral patterns
		</p>
	</div>

	<div class="mb-8">
		<h3 class="mb-3 text-sm font-semibold tracking-wide text-slate-500 uppercase">
			Coaching Narrative
		</h3>
		<div class="prose prose-slate prose-sm max-w-none space-y-3 text-slate-700">
			{#each coaching.narrative.split('\n\n') as paragraph}
				<p>{paragraph}</p>
			{/each}
		</div>
	</div>

	<div>
		<h3 class="mb-4 text-sm font-semibold tracking-wide text-slate-500 uppercase">
			Your Trading Rulebook
		</h3>
		<div class="space-y-4">
			{#each coaching.rules as rule}
				<div class="rounded-lg border border-slate-200 p-4">
					<div class="flex items-start gap-3">
						<div
							class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-brand text-xs font-bold text-white"
						>
							{rule.number}
						</div>
						<div>
							<h4 class="font-semibold text-slate-900">{rule.title}</h4>
							<p class="mt-1 text-sm text-slate-600">{rule.description}</p>
							<p class="mt-2 text-xs text-slate-400 italic">Evidence: {rule.evidence}</p>
						</div>
					</div>
				</div>
			{/each}
		</div>
	</div>
</Card>
